# Theme: Ariadne
$error = rgba(ff6048ff)
$on_tertiary = rgba(040e0dff)
$inverse_surface = rgba(f5e2c5ff)
$tertiary_container = rgba(0f211fff)
$source_color = rgba(7ad9a8ff)
$background = rgba(0a1816ff)
$surface_variant = rgba(0f211fff)
$surface_container_lowest = rgba(040e0dff)
$secondary_fixed = rgba(e89aa8ff)
$inverse_primary = rgba(7ad9a8ff)
$surface_container = rgba(0f211fff)
$surface_container_high = rgba(152a26ff)
$on_secondary_fixed_variant = rgba(0a1816ff)
$on_secondary_container = rgba(e89aa8ff)
$on_tertiary_container = rgba(5fc8d4ff)
$surface_bright = rgba(1d3631ff)
$inverse_on_surface = rgba(040e0dff)
$tertiary_fixed_dim = rgba(40a8b4ff)
$tertiary_fixed = rgba(5fc8d4ff)
$on_secondary = rgba(040e0dff)
$surface_tint = rgba(7ad9a8ff)
$primary_fixed_dim = rgba(5cb88aff)
$surface_container_highest = rgba(1d3631ff)
$outline_variant = rgba(152a26ff)
$secondary_container = rgba(0f211fff)
$on_tertiary_fixed_variant = rgba(0a1816ff)
$surface_dim = rgba(0a1816ff)
$on_primary_container = rgba(7ad9a8ff)
$on_primary_fixed = rgba(040e0dff)
$shadow = rgba(000000ff)
$on_primary = rgba(040e0dff)
$on_tertiary_fixed = rgba(040e0dff)
$secondary = rgba(e89aa8ff)
$on_error_container = rgba(ff6048ff)
$on_surface = rgba(f5e2c5ff)
$surface_container_low = rgba(0a1816ff)
$scrim = rgba(000000ff)
$on_error = rgba(040e0dff)
$on_primary_fixed_variant = rgba(0a1816ff)
$primary_container = rgba(0f211fff)
$primary_fixed = rgba(7ad9a8ff)
$tertiary = rgba(5fc8d4ff)
$secondary_fixed_dim = rgba(c77a88ff)
$primary = rgba(7ad9a8ff)
$outline = rgba(5a4d3eff)
$error_container = rgba(0f211fff)
$on_surface_variant = rgba(c4b09aff)
$surface = rgba(0a1816ff)
$on_secondary_fixed = rgba(040e0dff)
