# Theme: Everforest
$error = rgba(e67e80ff)
$on_tertiary = rgba(2d353bff)
$inverse_surface = rgba(d3c6aaff)
$tertiary_container = rgba(3d484dff)
$source_color = rgba(a7c080ff)
$background = rgba(2d353bff)
$surface_variant = rgba(3d484dff)
$surface_container_lowest = rgba(1e2326ff)
$secondary_fixed = rgba(d3c6aaff)
$inverse_primary = rgba(a7c080ff)
$surface_container = rgba(3d484dff)
$surface_container_high = rgba(4d5a5fff)
$on_secondary_fixed_variant = rgba(1e2326ff)
$on_secondary_container = rgba(d3c6aaff)
$on_tertiary_container = rgba(7fbbb3ff)
$surface_bright = rgba(4d5a5fff)
$inverse_on_surface = rgba(1e2326ff)
$tertiary_fixed_dim = rgba(6a9e97ff)
$tertiary_fixed = rgba(7fbbb3ff)
$on_secondary = rgba(2d353bff)
$surface_tint = rgba(a7c080ff)
$primary_fixed_dim = rgba(899c6bff)
$surface_container_highest = rgba(5f6c71ff)
$outline_variant = rgba(4d5a5fff)
$secondary_container = rgba(3d484dff)
$on_tertiary_fixed_variant = rgba(1e2326ff)
$surface_dim = rgba(2d353bff)
$on_primary_container = rgba(a7c080ff)
$on_primary_fixed = rgba(2d353bff)
$shadow = rgba(000000ff)
$on_primary = rgba(2d353bff)
$on_tertiary_fixed = rgba(2d353bff)
$secondary = rgba(d3c6aaff)
$on_error_container = rgba(e67e80ff)
$on_surface = rgba(d3c6aaff)
$surface_container_low = rgba(232a2eff)
$scrim = rgba(000000ff)
$on_error = rgba(2d353bff)
$on_primary_fixed_variant = rgba(1e2326ff)
$primary_container = rgba(3d484dff)
$primary_fixed = rgba(a7c080ff)
$tertiary = rgba(7fbbb3ff)
$secondary_fixed_dim = rgba(b8b094ff)
$primary = rgba(a7c080ff)
$outline = rgba(5f6c71ff)
$error_container = rgba(3d484dff)
$on_surface_variant = rgba(a6b0a0ff)
$surface = rgba(2d353bff)
$on_secondary_fixed = rgba(2d353bff)
