# hyprtoolkit general theming
# Used by hypr* Qt6 apps for colors, fonts, rounding

general {
    icon_theme = Papirus
    font_family = Sans Serif
    font_family_monospace = JetBrainsMono Nerd Font
    rounding_large = 12
    rounding_small = 8
}

theme {
    background = 0xFF181818
    base = 0xFF202020
    text = 0xFFDADADA
    alternate_base = 0xFF272727
    bright_text = 0xFFFFDEDE
    accent = 0xFFa7c080
    accent_secondary = 0xFF7aa2f7
}
