#source = colors.conf
general {
  lock_on_suspend = true
}

background {
    monitor =
    path = ~/Pictures/wallpaper/1363709.png
    blur_size = 10
    blur_passes = 3
}

# greeting
#label {
#    monitor =
#    text = cmd[update:60000:true] echo "<span font_family='Betterlett' font_weight='400'>$(hour=$(date +'%H'); if [ $hour -lt 12 ]; then echo 'Good Morning'; elif [ $hour -lt 17 ]; then echo 'Good Afternoon'; else echo 'Good Evening'; fi)</span>"
#    color = rgba(ffb3b0ff)
#    font_size = 75
#    position = 0, 140
#    halign = center
#    valign = center
#}

# hour
label {
    monitor =
    text = cmd[update:1000:true] echo "<span font_family='SF Pro Display' font_weight='700'>$(date +'%I:%M')</span>"
    color = rgba(ffb3b0ff)
    font_size = 150
    position = 0, 120
    halign = center
    valign = center
}

# minute
#label {
 #   monitor =
  #  text = cmd[update:1000:true] echo "<span font_family='SF Pro Display' font_weight='700'>$(date +'%M')</span>"
   # color = rgba(e7bdbaff)
#    font_size = 75
 #   position = 0, 30
  #  halign = center
   # valign = center
#}

# date
label {
    monitor =
    text = cmd[update:60000:true] echo "<span font_family='SF Pro Display' font_weight='400'>$(date +'%A, %B %d')</span>"
    color = rgba(c2c7ceff)
    font_size = 18
    position = 0, 20
    halign = center
    valign = center
}

# input field
input-field {
    monitor =
    size = 13%, 4%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(1a1111ff) rgba(904a48ff) 45deg
    check_color = rgba(f0deddff) rgba(733332ff) 120deg
    fail_color = rgba(ffb4abff)
    font_color = rgba(e7bdbaff)
    fade_on_empty = true
    placeholder_text = Password Please :)
    rounding = 35
    show_on_input = true
    position = 0, -40
    halign = center
    valign = center
}

animations {
    enabled = true
    bezier = myBezier, 0.42, 0, 1, 1
    animation = fadeIn, 1, 1.5, myBezier
    animation = fadeOut, 1, 1.5, myBezier
    animation = inputFieldFade, 1, 1.5, myBezier
}   
