
-- ################
-- ## AUTOSTART ###
-- ################
hl.on("hyprland.start", function()
	hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("/usr/lib/xdg-desktop-portal-gtk")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("wl-paste --watch cliphist store")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("awww-daemon")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("hypridle")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("nm-applet") -- tray icon for quick network menu
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("kdeconnectd")
end)
-- Ghostty daemon is handled by its systemd unit (graphical-session.target)
-- hl.exec_cmd("ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false")
hl.on("hyprland.start", function()
	hl.exec_cmd("brave-browser --restore-last-session")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("matuwall --daemon")
end)
--hl.on("hyprland.start", function()
--	hl.exec_cmd("cava-bg on")
--end)
hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload")
end)
hl.on("hyprland.start", function()
	hl.exec_cmd("eww daemon && sleep 0.3 && eww open clock")
end)