-- ########################
-- ## THEME COLORS #######
-- ########################

-- Read theme colors from colors.conf (regenerated by theme-switcher)
local function load_theme_colors()
	local vars = {}
	local home = os.getenv("HOME")
	local file = io.open(home .. "/.config/hypr/colors.conf", "r")
	if not file then
		return vars
	end
	for line in file:lines() do
		local var, val = line:match("^%$(%w+) = rgba%((%x+)%)$")
		if var then
			vars[var] = val
		end
	end
	file:close()
	return vars
end

local theme = load_theme_colors()

-- Get theme color with custom alpha, fallback to default
local function col(var, alpha, fallback)
	local c = theme[var]
	if c then
		return "rgba(" .. c:sub(1, 6) .. alpha .. ")"
	end
	return fallback
end

-- Border colors follow theme: active uses primary→tertiary gradient, inactive is transparent
local BORDER_ACTIVE_1 = col("primary", "ee", "rgba(cba6f7ee)")
local BORDER_ACTIVE_2 = col("tertiary", "ee", "rgba(a6e3a1ee)")

-- #####################
-- ## DECORATION ########
-- #####################

hl.config({
	decoration = {
		rounding = 20,
		rounding_power = 7,
		dim_special = 0.05,
		dim_strength = 0.3,
		blur = {
			brightness = 0.40,
			contrast = 0.8,
			ignore_opacity = 0,
			noise = 0.02,
			passes = 6,
			popups = 1,
			size = 2,
			special = 1,
			vibrancy = 0.35,
			vibrancy_darkness = 0.8,
		},
		shadow = {
			enabled = true,
			offset = "0 0",
			range = 20,
			render_power = 3,
			color = 0xee121212,
		},
	},
})


-- ####################
-- ## LOOK AND FEEL ###
-- ####################
--  Refer to https://wiki.hypr.land/Configuring/Variables/

-- ###############
-- ## GENERAL ####
-- ###############
hl.config({
	general = {
		extend_border_grab_area = 20,
		gaps_in = 6,
		gaps_out = 6,
		resize_on_border = true,
		allow_tearing = false,
		border_size = 1,
		col = {
			active_border = { colors = {BORDER_ACTIVE_1}},
			inactive_border = "rgba(00000000)",
		},
	},
})
